### PR TITLE
fixed bug of settings not updating, close #123

### LINKED ISSUE #123: When opening existing timeline, settings are not updated
When opening an existing timeline, the saved settings are not displayed on the settings tab, instead the settings are always the same: Joon, 200 and the packing option unticked.

### PR DESCRIPTION
**Pull request by mannapuder**
close #123

### CODE REVIEW

**Review by krlkngro — APPROVED** [review]

File: src/main/java/ee/ut/controllers/GeneralSettingsController.java [hunk 1]
```diff
@@ -30,14 +32,21 @@
...
+            if (!newValue.matches("\\d{0,5}")) {
+                eventSpace.setText(oldValue);
             }
         });
+        Data data = App.getData();
+        this.labelType.setValue( switch(data.getLabelType().toString()){
+            case "line" -> "Joon";
+            case "text" -> "Tekst";
+            case "dot" -> "Punkt";
+            default -> "appi";
```
Comment (krlkngro) [inline src/main/java/ee/ut/controllers/GeneralSettingsController.java:45]: not really appropriate

**Review by krlkngro — APPROVED** [review]
